# Generated by Django 4.1.7 on 2023-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directormodel',
            name='deathDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
