# Generated by Django 4.1.7 on 2023-03-19 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors_api', '0001_initial'),
        ('movies_api', '0002_moviemodel_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors_api.actormodel')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_api.moviemodel')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
