# Generated by Django 4.1.7 on 2023-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodel',
            name='character_name',
            field=models.CharField(default='Extra', max_length=255),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
