# Generated by Django 4.1.7 on 2023-03-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actormodel',
            name='deathDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
