# Generated by Django 4.1.7 on 2023-03-12 21:06

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('releaseDate', models.DateTimeField()),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['-releaseDate'],
            },
        ),
    ]
