# Generated by Django 4.1.7 on 2023-03-12 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directors_api', '0001_initial'),
        ('movies_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directors_api.directormodel'),
        ),
    ]
